[2022-07-28 21:22:43,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.venv manual__2022-07-29T01:22:42.242364+00:00 [queued]>
[2022-07-28 21:22:44,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.venv manual__2022-07-29T01:22:42.242364+00:00 [queued]>
[2022-07-28 21:22:44,000] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 21:22:44,001] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 21:22:44,001] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 21:22:44,012] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): venv> on 2022-07-29 01:22:42.242364+00:00
[2022-07-28 21:22:44,013] {standard_task_runner.py:52} INFO - Started process 11114 to run task
[2022-07-28 21:22:44,016] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'venv', 'manual__2022-07-29T01:22:42.242364+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp586ecdir', '--error-file', '/tmp/tmp7vg28qaf']
[2022-07-28 21:22:44,016] {standard_task_runner.py:80} INFO - Job 22: Subtask venv
[2022-07-28 21:22:44,043] {task_command.py:370} INFO - Running <TaskInstance: my_dag.venv manual__2022-07-29T01:22:42.242364+00:00 [running]> on host DESKTOP-5GAFI6N.localdomain
[2022-07-28 21:22:44,081] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=venv
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T01:22:42.242364+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T01:22:42.242364+00:00
[2022-07-28 21:22:44,081] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-28 21:22:44,082] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'source /home/lemon/main/Assignment4/dataperf-vision-debugging/.venv/bin/activate.fish']
[2022-07-28 21:22:44,085] {subprocess.py:85} INFO - Output:
[2022-07-28 21:22:44,085] {subprocess.py:92} INFO - /home/lemon/main/Assignment4/dataperf-vision-debugging/.venv/bin/activate.fish: line 4: syntax error near unexpected token `-d'
[2022-07-28 21:22:44,085] {subprocess.py:92} INFO - /home/lemon/main/Assignment4/dataperf-vision-debugging/.venv/bin/activate.fish: line 4: `function deactivate  -d "Exit virtualenv and return to normal shell environment"'
[2022-07-28 21:22:44,086] {subprocess.py:96} INFO - Command exited with return code 2
[2022-07-28 21:22:44,091] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lemon/airflow/airflowenv/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-28 21:22:44,092] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=my_dag, task_id=venv, execution_date=20220729T012242, start_date=20220729T012243, end_date=20220729T012244
[2022-07-28 21:22:44,102] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task venv (Bash command failed. The command returned a non-zero exit code 2.; 11114)
[2022-07-28 21:22:44,108] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 21:22:44,119] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
