[2022-07-28 21:54:07,576] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.dataperf manual__2022-07-29T01:54:04.317014+00:00 [queued]>
[2022-07-28 21:54:07,579] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.dataperf manual__2022-07-29T01:54:04.317014+00:00 [queued]>
[2022-07-28 21:54:07,579] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 21:54:07,579] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 21:54:07,579] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 21:54:07,589] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): dataperf> on 2022-07-29 01:54:04.317014+00:00
[2022-07-28 21:54:07,590] {standard_task_runner.py:52} INFO - Started process 16462 to run task
[2022-07-28 21:54:07,592] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'dataperf', 'manual__2022-07-29T01:54:04.317014+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpt8bvx7xy', '--error-file', '/tmp/tmpkprpmhf7']
[2022-07-28 21:54:07,592] {standard_task_runner.py:80} INFO - Job 40: Subtask dataperf
[2022-07-28 21:54:07,612] {task_command.py:370} INFO - Running <TaskInstance: my_dag.dataperf manual__2022-07-29T01:54:04.317014+00:00 [running]> on host DESKTOP-5GAFI6N.localdomain
[2022-07-28 21:54:07,639] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dataperf
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T01:54:04.317014+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T01:54:04.317014+00:00
[2022-07-28 21:54:07,640] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-28 21:54:07,640] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /home/lemon/main/Assignment4/dataperf-vision-debugging/create_baselines.py && python3 /home/lemon/main/Assignment4/dataperf-vision-debugging/main.py && python3 /home/lemon/main/Assignment4/dataperf-vision-debugging/plotter.py']
[2022-07-28 21:54:07,642] {subprocess.py:85} INFO - Output:
[2022-07-28 21:54:07,726] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-07-28 21:54:07,726] {subprocess.py:92} INFO -   File "/home/lemon/main/Assignment4/dataperf-vision-debugging/create_baselines.py", line 7, in <module>
[2022-07-28 21:54:07,726] {subprocess.py:92} INFO -     from pyarrow import parquet as pq
[2022-07-28 21:54:07,726] {subprocess.py:92} INFO - ModuleNotFoundError: No module named 'pyarrow'
[2022-07-28 21:54:07,736] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-28 21:54:07,741] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lemon/airflow/airflowenv/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-28 21:54:07,742] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=my_dag, task_id=dataperf, execution_date=20220729T015404, start_date=20220729T015407, end_date=20220729T015407
[2022-07-28 21:54:07,751] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task dataperf (Bash command failed. The command returned a non-zero exit code 1.; 16462)
[2022-07-28 21:54:07,764] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-28 21:54:07,783] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
